<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'color' => NULL,
                'created_at' => '2020-09-28 20:27:58',
                'icon_class' => 'voyager-boat',
                'id' => 1,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.dashboard',
                'target' => '_self',
                'title' => 'Dashboard',
                'updated_at' => '2020-09-28 20:27:58',
                'url' => '',
            ),
            1 => 
            array (
                'color' => NULL,
                'created_at' => '2020-09-28 20:27:58',
                'icon_class' => 'voyager-images',
                'id' => 2,
                'menu_id' => 1,
                'order' => 11,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.media.index',
                'target' => '_self',
                'title' => 'Media',
                'updated_at' => '2020-12-16 17:14:29',
                'url' => '',
            ),
            2 => 
            array (
                'color' => NULL,
                'created_at' => '2020-09-28 20:27:58',
                'icon_class' => 'voyager-person',
                'id' => 3,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.users.index',
                'target' => '_self',
                'title' => 'Users',
                'updated_at' => '2020-09-28 20:27:58',
                'url' => '',
            ),
            3 => 
            array (
                'color' => NULL,
                'created_at' => '2020-09-28 20:27:59',
                'icon_class' => 'voyager-lock',
                'id' => 4,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.roles.index',
                'target' => '_self',
                'title' => 'Roles',
                'updated_at' => '2020-09-28 20:27:59',
                'url' => '',
            ),
            4 => 
            array (
                'color' => NULL,
                'created_at' => '2020-09-28 20:27:59',
                'icon_class' => 'voyager-tools',
                'id' => 5,
                'menu_id' => 1,
                'order' => 12,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Tools',
                'updated_at' => '2020-12-16 17:14:01',
                'url' => '',
            ),
            5 => 
            array (
                'color' => NULL,
                'created_at' => '2020-09-28 20:27:59',
                'icon_class' => 'voyager-list',
                'id' => 6,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.menus.index',
                'target' => '_self',
                'title' => 'Menu Builder',
                'updated_at' => '2020-12-16 17:13:36',
                'url' => '',
            ),
            6 => 
            array (
                'color' => NULL,
                'created_at' => '2020-09-28 20:27:59',
                'icon_class' => 'voyager-data',
                'id' => 7,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.database.index',
                'target' => '_self',
                'title' => 'Database',
                'updated_at' => '2020-12-16 17:13:36',
                'url' => '',
            ),
            7 => 
            array (
                'color' => NULL,
                'created_at' => '2020-09-28 20:28:00',
                'icon_class' => 'voyager-compass',
                'id' => 8,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.compass.index',
                'target' => '_self',
                'title' => 'Compass',
                'updated_at' => '2020-12-16 17:13:36',
                'url' => '',
            ),
            8 => 
            array (
                'color' => NULL,
                'created_at' => '2020-09-28 20:28:00',
                'icon_class' => 'voyager-bread',
                'id' => 9,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.bread.index',
                'target' => '_self',
                'title' => 'BREAD',
                'updated_at' => '2020-12-16 17:13:36',
                'url' => '',
            ),
            9 => 
            array (
                'color' => NULL,
                'created_at' => '2020-09-28 20:28:00',
                'icon_class' => 'voyager-settings',
                'id' => 10,
                'menu_id' => 1,
                'order' => 13,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.settings.index',
                'target' => '_self',
                'title' => 'Settings',
                'updated_at' => '2020-12-16 17:14:01',
                'url' => '',
            ),
            10 => 
            array (
                'color' => NULL,
                'created_at' => '2020-09-28 20:28:38',
                'icon_class' => 'voyager-categories',
                'id' => 11,
                'menu_id' => 1,
                'order' => 7,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.categories.index',
                'target' => '_self',
                'title' => 'Categories',
                'updated_at' => '2020-12-16 17:14:28',
                'url' => '',
            ),
            11 => 
            array (
                'color' => NULL,
                'created_at' => '2020-09-28 20:28:44',
                'icon_class' => 'voyager-news',
                'id' => 12,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.posts.index',
                'target' => '_self',
                'title' => 'Posts',
                'updated_at' => '2020-12-16 17:14:28',
                'url' => '',
            ),
            12 => 
            array (
                'color' => NULL,
                'created_at' => '2020-09-28 20:28:49',
                'icon_class' => 'voyager-file-text',
                'id' => 13,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.pages.index',
                'target' => '_self',
                'title' => 'Pages',
                'updated_at' => '2020-12-16 17:14:28',
                'url' => '',
            ),
            13 => 
            array (
                'color' => NULL,
                'created_at' => '2020-09-28 20:29:00',
                'icon_class' => 'voyager-hook',
                'id' => 14,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.hooks',
                'target' => '_self',
                'title' => 'Hooks',
                'updated_at' => '2020-12-16 17:13:36',
                'url' => '',
            ),
            14 => 
            array (
                'color' => NULL,
                'created_at' => '2020-09-29 11:29:24',
                'icon_class' => 'voyager-window-list',
                'id' => 15,
                'menu_id' => 1,
                'order' => 9,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.product-orders.index',
                'target' => '_self',
                'title' => 'Product Orders',
                'updated_at' => '2020-12-16 17:14:29',
                'url' => '',
            ),
            15 => 
            array (
                'color' => '#000000',
                'created_at' => '2020-09-29 13:01:43',
                'icon_class' => 'voyager-hammer',
                'id' => 16,
                'menu_id' => 1,
                'order' => 10,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'voyager.orders.index',
                'target' => '_self',
                'title' => 'Orders',
                'updated_at' => '2020-12-16 17:14:29',
                'url' => '',
            ),
            16 => 
            array (
                'color' => '#000000',
                'created_at' => '2020-12-16 14:22:28',
                'icon_class' => 'voyager-shop',
                'id' => 17,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'voyager.shops.index',
                'target' => '_self',
                'title' => 'Shops',
                'updated_at' => '2020-12-16 17:15:10',
                'url' => '',
            ),
            17 => 
            array (
                'color' => '#000000',
                'created_at' => '2020-12-16 17:04:30',
                'icon_class' => 'voyager-dot-3',
                'id' => 18,
                'menu_id' => 1,
                'order' => 8,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'voyager.products.index',
                'target' => '_self',
                'title' => 'Products',
                'updated_at' => '2020-12-16 17:16:50',
                'url' => '',
            ),
        ));
        
        
    }
}